In [21]:
import pandas as pd
import numpy as np
data = pd.read_csv("raw_predictors_until2013.csv")
data

yyyymm     Index      D12       E12       b/m     tbl     AAA     BAA  \
0     192701     13.21   0.6967    1.2290  0.443706  0.0323  0.0466  0.0561   
1     192702     13.84   0.7033    1.2180  0.428501  0.0329  0.0467  0.0559   
2     192703     13.93   0.7100    1.2080  0.469765  0.0320  0.0462  0.0554   
3     192704     14.17   0.7167    1.1970  0.456754  0.0339  0.0458  0.0548   
4     192705     14.91   0.7233    1.1860  0.434783  0.0333  0.0457  0.0550   
5     192706     14.77   0.7300    1.1750  0.452385  0.0307  0.0458  0.0555   
6     192707     15.73   0.7367    1.1640  0.414553  0.0296  0.0460  0.0555   
7     192708     16.43   0.7433    1.1530  0.396227  0.0270  0.0456  0.0548   
8     192709     17.14   0.7500    1.1430  0.380586  0.0268  0.0454  0.0542   
9     192710     16.23   0.7567    1.1320  0.413801  0.0308  0.0451  0.0538   
10    192711     17.33   0.7633    1.1210  0.379396  0.0304  0.0449  0.0535   
11    192712     17.66   0.7700    1.1100  0.374689  0.0317  0.0446  0.0532   
12    192801     17.57   0.7767    1.1330  0.378670  0.0331  0.0446  0.0535   
13    192802     17.26   0.7833    1.1550  0.386077  0.0333  0.0446  0.0533   
14    192803     19.13   0.7900    1.1770  0.363255  0.0327  0.0446  0.0532   
15    192804     19.75   0.7967    1.2000  0.368095  0.0362  0.0446  0.0533   
16    192805     20.00   0.8033    1.2220  0.354397  0.0390  0.0449  0.0542   
17    192806     19.19   0.8100    1.2450  0.370300  0.0392  0.0457  0.0555   
18    192807     19.43   0.8167    1.2680  0.360648  0.0412  0.0461  0.0558   
19    192808     20.87   0.8233    1.2900  0.324030  0.0436  0.0464  0.0561   
20    192809     21.37   0.8300    1.3120  0.328166  0.0457  0.0461  0.0559   
21    192810     21.68   0.8367    1.3350  0.308931  0.0470  0.0461  0.0558   
22    192811     24.28   0.8433    1.3570  0.265526  0.0426  0.0458  0.0555   
23    192812     24.35   0.8500    1.3800  0.259667  0.0426  0.0461  0.0560   
24    192901     25.74   0.8600    1.3990  0.245347  0.0466  0.0462  0.0563   
25    192902     25.59   0.8700    1.4180  0.245424  0.0439  0.0466  0.0566   
26    192903     25.53   0.8800    1.4380  0.272300  0.0460  0.0470  0.0579   
27    192904     25.94   0.8900    1.4570  0.263397  0.0480  0.0469  0.0580   
28    192905     24.83   0.9000    1.4760  0.282775  0.0509  0.0470  0.0580   
29    192906     27.62   0.9100    1.4950  0.253581  0.0480  0.0477  0.0594   
...      ...       ...      ...       ...       ...     ...     ...     ...   
1062  201507  2,103.84  41.9981   93.4933  0.308953  0.0003  0.0415  0.0520   
1063  201508  1,972.18  42.2543   92.0767  0.330671  0.0007  0.0404  0.0519   
1064  201509  1,920.03  42.5104   90.6600  0.335612  0.0002  0.0407  0.0534   
1065  201510  2,079.36  42.8029   89.2833  0.309414  0.0002  0.0395  0.0534   
1066  201511  2,080.41  43.0954   87.9067  0.308429  0.0012  0.0406  0.0546   
1067  201512  2,043.94  43.3879   86.5300  0.313649  0.0023  0.0397  0.0546   
1068  201601  1,940.24  43.5506   86.5000  0.331911  0.0026  0.0400  0.0545   
1069  201602  1,932.23  43.7133   86.4700  0.330902  0.0031  0.0396  0.0534   
1070  201603  2,059.74  43.8759   86.4400  0.327955  0.0029  0.0382  0.0513   
1071  201604  2,065.30  44.0706   86.6000  0.326321  0.0023  0.0362  0.0479   
1072  201605  2,096.95  44.2652   86.7600  0.326072  0.0027  0.0365  0.0468   
1073  201606  2,098.86  44.4599   86.9200  0.323475  0.0027  0.0350  0.0453   
1074  201607  2,173.60  44.6485   87.6433  0.314661  0.0030  0.0328  0.0422   
1075  201608  2,170.95  44.8371   88.3667  0.315197  0.0030  0.0332  0.0424   
1076  201609  2,168.27  45.0257   89.0900  0.316794  0.0029  0.0341  0.0431   
1077  201610  2,126.15  45.2507   90.9100  0.319688  0.0033  0.0351  0.0438   
1078  201611  2,198.81  45.4756   92.7300  0.303286  0.0045  0.0386  0.0471   
1079  201612  2,238.83  45.7006   94.5500  0.293479  0.0051  0.0406  0.0483   
1080  201701  2,278.87  45.9279   96.4633  0.291980  0.0

1092

In [6]:
sLength = len(data['yyyymm'])
# add the bullMarket column with random ints (to be replaced in next cell)
data['bull'] = pd.Series(np.random.randn(sLength), index=data.index)
# Create bullMarkert for ret_sp500+1
bull = []
for data in data['CRSP_SPvw']:
    if data > 0:
        bull.append(1)
    else:
        bull.append(0)
data['bull'] = bull

data.shape

TypeError: 'float' object is not subscriptable

In [3]:

# Rename columns
sp500.columns = ['Date', 'sp500', 'sp500+1','ret_sp500', 'ret_sp500+1']
sp500 = sp500.dropna()
sLength = len(sp500['Date'])
# add the bullMarket column with random ints (to be replaced in next cell)
sp500['bullMarket'] = pd.Series(np.random.randn(sLength), index=sp500.index)

# Create bullMarkert for ret_sp500+1
bull = []
for data in sp500['ret_sp500+1']:
    if data > 0:
        bull.append(1)
    else:
        bull.append(0)
sp500['bullMarket'] = bull
# print(sp500)

sp500.shape
# print(sp500)

(14275, 6)

In [27]:
tdata = pd.read_csv("Total_Data_no_dots.csv",low_memory=False)

result = pd.merge(sp500, tdata, on='Date', how='left')

result  = result.dropna()

# assume we want to predict the raw index of sp500 at T+1, given all the info at T

y_reg = result['ret_sp500+1']

y_cal = result['bullMarket']
 
# list(result)

result = result.drop(columns=['VOX Close', 'DGS1', 'DGS10', 'T10Y2Y', 'DBAA', 'USD1MTD156N', 'DCOILBRENTEU', 'DTWEXB', 'DEXUSEU', 'T10YIE', 'T5YIFR', 'BAMLH0A0HYM2EY'])

x = result.drop(columns=['Date','sp500_x','sp500+1','ret_sp500+1','Unnamed: 0'])

# print(result.dtypes)

In [29]:
# Linear Regression Model

from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.cross_validation import KFold

kf = KFold(x.shape[0], n_folds=2, shuffle=True)

for train_index, test_index in kf:
    x_train, x_test = x.iloc[train_index], x.iloc[test_index]
    y_train, y_test = y_reg.iloc[train_index], y_reg.iloc[test_index]
    y_train_cal, y_test_cal = y_cal.iloc[train_index], y_cal.iloc[test_index]

    regr = linear_model.LinearRegression()
    regr.fit(x_train, y_train)

    y_pred = regr.predict(x_test)
    print("MSE: ", mean_squared_error(y_test, y_pred))
    
print( "the main take way: the mean squared error is always within 1% ")


MSE:  0.8108592714839336
MSE:  0.8220161493992437
the main take way: the mean squared error is always within 1% 


In [31]:
# clssification 

# decision tree CART algorithm

from sklearn import tree
from sklearn.metrics import confusion_matrix
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train_cal)
predicted = clf.predict(x_test)
# print (predicted)
c_matrix = confusion_matrix(predicted,y_test_cal)
precision = c_matrix[1,1]/(c_matrix[1,1]+c_matrix[0,1])
recall= c_matrix[1,1]/(c_matrix[1,1]+c_matrix[1,0])

print(c_matrix)  

print("precision: ", precision)  
print("recall: ", recall)  

print( "the main take way: 'perfect' prediction, overfitting problem")


[[2132    0]
 [   0 2242]]
precision:  1.0
recall:  1.0
the main take way: 'perfect' prediction, overfitting problem


In [26]:
# naive Bayes 
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train, y_train_cal).predict(x_test)

predicted= gnb.predict(x_test)

c_matrix = confusion_matrix(predicted,y_test_cal)
precision = c_matrix[1,1]/(c_matrix[1,1]+c_matrix[0,1])
recall= c_matrix[1,1]/(c_matrix[1,1]+c_matrix[1,0])

print(c_matrix)  

print("precision: ", precision)  
print("recall: ", recall)  

print( "the main take way: High Precision, recall is slightly better than a coin flip")

[[ 120  143]
 [2012 2099]]
precision:  0.9362176628010704
recall:  0.5105813670639747


In [34]:
# Support Vector Classification

from sklearn.svm import SVC
clf = SVC(gamma='auto')
clf.fit(x_train, y_train_cal) 

predicted= clf.predict(x_test)

c_matrix = confusion_matrix(predicted,y_test_cal)
precision = c_matrix[1,1]/(c_matrix[1,1]+c_matrix[0,1])
recall= c_matrix[1,1]/(c_matrix[1,1]+c_matrix[1,0])

print(c_matrix)  

print("precision: ", precision)  
print("recall: ", recall)  

print( "the main take way: High Precision, recall is way more better than naive Bayes ")

[[1063    0]
 [1069 2242]]
precision:  1.0
recall:  0.6771368166717004
the main take way: High Precision, recall is way more better than naive Bayes 
